// Auto-generated image manifest
export const images = [
  { src: "/images/irl-01.jpg", caption: "Community Gathering" },
  { src: "/images/x-posts.jpg", caption: "BCSA X Posts" },
  { src: "/images/irl-02.jpg", caption: "On the Ground" },
  { src: "/images/event-01.jpg", caption: "Chapter Event" },
  { src: "/images/event-02.jpg", caption: "Chapter Event" },
  { src: "/images/event-03.jpg", caption: "Chapter Event" },
  { src: "/images/council.jpg", caption: "Council Proposal" },
  { src: "/images/event-04.jpg", caption: "Community Session" },
  { src: "/images/event-05.jpg", caption: "Community Session" },
  { src: "/images/event-06.jpg", caption: "Activation" },
  { src: "/images/malawi.jpg", caption: "Malawi Session" },
  { src: "/images/event-07.jpg", caption: "Workshop" },
  { src: "/images/event-08.jpg", caption: "Builder Session" },
  { src: "/images/event-09.jpg", caption: "Chapter Meetup" },
  { src: "/images/event-10.jpg", caption: "BCSA Activity" },
  { src: "/images/event-11.jpg", caption: "Community Work" },
  { src: "/images/event-12.jpg", caption: "BCSA Southern Africa" },
  { src: "/images/event-13.jpg", caption: "Regional Activation" },
  { src: "/images/irl-03.jpg", caption: "Community Moment" },
  { src: "/images/wa-01.jpg", caption: "WhatsApp Community" },
  { src: "/images/wa-02.jpg", caption: "WhatsApp Groups" },
  { src: "/images/reg-meeting.jpg", caption: "Regional Meeting" },
  { src: "/images/members.jpg", caption: "Community Members" },
  { src: "/images/wa-03.jpg", caption: "Community Info" },
  { src: "/images/x-profile.jpg", caption: "@BCSA_Region X Profile" },
  { src: "/images/discord.jpg", caption: "Discord Gathering" },
  { src: "/images/content-lab.jpg", caption: "Content Creation Lab" },
  { src: "/images/based-mornings.jpg", caption: "Based Mornings" },
  { src: "/images/east-africa.jpg", caption: "East Africa Meeting" },
  { src: "/images/bukelo.jpg", caption: "Community Endorsement" },
  { src: "/images/linkup.jpg", caption: "BCSA Linkup" },
  { src: "/images/batches.jpg", caption: "Base Batches 003" },
  { src: "/images/groups.jpg", caption: "WhatsApp Groups" },
  { src: "/images/comm-info.jpg", caption: "69 Members" },
  { src: "/images/fireside.jpg", caption: "First Fireside Call" },
  { src: "/images/reg-flyer.jpg", caption: "Regional Meeting Flyer" },
  { src: "/images/xtra-01.jpg", caption: "BCSA Moment" },
  { src: "/images/xtra-02.jpg", caption: "BCSA Moment" },
  { src: "/images/xtra-03.jpg", caption: "BCSA Moment" },
  { src: "/images/xtra-04.jpg", caption: "BCSA Moment" },
  { src: "/images/xtra-05.jpg", caption: "BCSA Moment" },
  { src: "/images/bobbi.jpg", caption: "Bobbi Andrea" },
];

export const irlPhotos = ["irl-01.jpg", "irl-02.jpg", "event-01.jpg", "event-02.jpg", "event-03.jpg", "council.jpg", "event-04.jpg", "event-05.jpg", "event-06.jpg", "malawi.jpg", "event-07.jpg", "event-08.jpg", "event-09.jpg", "event-10.jpg", "event-11.jpg", "event-12.jpg", "event-13.jpg", "irl-03.jpg", "bobbi.jpg"];
export const socialPhotos = ["x-posts.jpg", "reg-meeting.jpg", "x-profile.jpg", "discord.jpg", "content-lab.jpg", "based-mornings.jpg", "east-africa.jpg", "bukelo.jpg", "linkup.jpg", "batches.jpg", "fireside.jpg", "reg-flyer.jpg"];
export const communityPhotos = ["wa-01.jpg", "wa-02.jpg", "members.jpg", "wa-03.jpg", "groups.jpg", "comm-info.jpg", "xtra-01.jpg", "xtra-02.jpg", "xtra-03.jpg", "xtra-04.jpg", "xtra-05.jpg"];
